# CHANGEME: Set these variable to your liking
title: Undermount AC for ESPHome
description: Install a ready-made ESPHome configuration on your Undermount AC ESPHome HVAC Controller
theme: jekyll-theme-slate
